# -*- rpm-spec -*-
BuildRoot:      /home/go_test/instance/sorter/src/entry/rpm_make/_CPack_Packages/RPM/entry-1.0-0.x86_64
Summary:        entry
Name:           entry
Version:        1.0
Release:        1
License:        unknown
Group:          unknown
Vendor:         unknown











%define _rpmdir /home/go_test/instance/sorter/src/entry/rpm_make/_CPack_Packages/RPM
%define _rpmfilename entry-1.0-0.x86_64.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /home/go_test/instance/sorter/src/entry/rpm_make/_CPack_Packages/RPM




%description
no package description available

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/home/go_test/instance/sorter/src/entry/rpm_make/_CPack_Packages/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/home/go_test/instance/sorter/src/entry/rpm_make/_CPack_Packages/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post


%postun


%pre


%preun


%files
%defattr(-,root,root,-)
%dir "/etc/sysconfig"
%dir "/etc/sysconfig/entry"
"/etc/sysconfig/entry/entry.cfg"
"/usr/bin/entry"
%dir "/usr/lib/systemd"
%dir "/usr/lib/systemd/system"
"/usr/lib/systemd/system/entry.service"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0-1
  Generated by CPack RPM (no Changelog file were provided)
